Update sugargame
This change also fixes the following Traceback that was caused when using the activity with newer pygame versions
-  Traceback (most recent call last):
  File "/home/dim/Activities/2-cars-activity/sugargame/event.py", line 128, in _keydown_cb
    return self._keyevent(widget, event, pygame.KEYDOWN)
  File "/home/dim/Activities/2-cars-activity/sugargame/event.py", line 169, in _keyevent
    mod = self._keymods()
  File "/home/dim/Activities/2-cars-activity/sugargame/event.py", line 145, in _keymods
    mod |= self.__keystate[key_val] and mod_val
IndexError: list index out of range